/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import entities.recipe;
import javax.swing.table.DefaultTableModel;
import static main.Main.chefs;
import static main.Main.recipes;
import static views.home.getSelectedRow;
import static views.home.home_table;

/**
 *
 * @author rycks
 */
public class addRecipe extends javax.swing.JFrame {

    /**
     * Creates new form addRecipe
     */
    // Método para agregar recetas a nuestro "almacenamiento"
    public void addRecipe(){
        // Creamos un objeto del tipo recipe
        recipe r1 = new recipe();
        // Tomamos los valores del formulario
        int id = recipes.size()+1;
        String name = r_name_txt.getText();
        String ing = r_ingredients_txt.getText();
        String prep = r_prep_txt.getText();
        int cid = getSelectedChef();
        if(checkEmpty()==0){
             // Asignamos valores al objeto
        r1.setId(id);
        r1.setName(name);
        r1.setIngredients(ing);
        r1.setPreparation(prep);
        r1.setCid(cid);
        // Empujamos el objeto en el almacenamiento (arraylist :p)
        recipes.add(r1);
        updateTable();
        }
    }
    
    public int checkEmpty(){
        int empty = 0;
        String name = views.addRecipe.r_name_txt.getText();
        String ingredients = r_ingredients_txt.getText();
        String preparation = r_prep_txt.getText();
        if("".equals(name)){
            name_msg.setText("Requerido");
            empty = 1;
        }else if(5>name.length()){
        name_msg.setText("Ingrese mas de 5 letras");
        empty = 1;
    } 
        if("".equals(ingredients)){
        ing_msg.setText("Requerido");
            empty = 1;
    }else if(25>ingredients.length()){
        ing_msg.setText("Ingrese al menos 25 caracteres");
            empty = 1;
    }
        if("".equals(preparation)){
        prep_msg.setText("Requerido");
            empty = 1;
    }else if(25>preparation.length()){
        prep_msg.setText("Ingrese al menos 25 caracteres");
            empty = 1;
    }
        return empty;
    }
    
    public int getSelectedChef(){
        String L3 = views.addRecipe.r_cb.getSelectedItem().toString();
        String L4 = Character.toString(L3.charAt(0));
        int L5 = Integer.parseInt(L4);
        System.out.println(L5);
       return L5;
    }
    
    public void updateTable(){
         DefaultTableModel model = (DefaultTableModel) views.home.home_table.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[3];
        for(int i = 0; i < recipes.size(); i++)
        {
            rowData[0] = recipes.get(i).getId();
            rowData[1] = recipes.get(i).getName();
            rowData[2] = chefs.get(recipes.get(i).getCid()-1).getName();
            
            model.addRow(rowData);
            home_table.setEnabled(true);
        }
    }
    public addRecipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        r_name_txt = new javax.swing.JTextField();
        r_cb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        r_ingredients_txt = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        r_prep_txt = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        name_msg = new javax.swing.JLabel();
        ing_msg = new javax.swing.JLabel();
        prep_msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Coffee Service", 0, 55)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LordOfTheFries");

        jLabel2.setFont(new java.awt.Font("Kirvy", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agregar receta");

        jLabel3.setText("Nombre:");

        r_name_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                r_name_txtMouseClicked(evt);
            }
        });

        for(int i = 0; i<chefs.size();i++){
            r_cb.addItem(chefs.get(i).getID()+") "+chefs.get(i).getName());

        }
        r_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_cbActionPerformed(evt);
            }
        });

        jLabel4.setText("Chef:");

        jLabel5.setText("Ingredientes:");

        r_ingredients_txt.setColumns(20);
        r_ingredients_txt.setRows(5);
        r_ingredients_txt.setSize(new java.awt.Dimension(240, 90));
        jScrollPane1.setViewportView(r_ingredients_txt);

        jLabel6.setText("Preparación:");

        r_prep_txt.setColumns(20);
        r_prep_txt.setRows(5);
        jScrollPane2.setViewportView(r_prep_txt);

        jButton1.setText("Agregar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Cancelar");

        name_msg.setForeground(new java.awt.Color(255, 51, 0));
        name_msg.setFocusable(false);
        name_msg.setVerifyInputWhenFocusTarget(false);

        ing_msg.setForeground(new java.awt.Color(255, 0, 0));

        prep_msg.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 202, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(r_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(r_name_txt, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ing_msg)
                            .addComponent(prep_msg))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r_name_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name_msg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(r_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ing_msg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prep_msg))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        addRecipe();
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void r_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_cbActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_r_cbActionPerformed

    private void r_name_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_r_name_txtMouseClicked
        // TODO add your handling code here:
        name_msg.setText("");
    }//GEN-LAST:event_r_name_txtMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel ing_msg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel name_msg;
    public static javax.swing.JLabel prep_msg;
    public static javax.swing.JComboBox<String> r_cb;
    private static javax.swing.JTextArea r_ingredients_txt;
    public static javax.swing.JTextField r_name_txt;
    private static javax.swing.JTextArea r_prep_txt;
    // End of variables declaration//GEN-END:variables
}
